spring.application.name=pruebatecnica
server.port=8080

# Completar o ajustar estas credenciales según el entorno MySQL asignado
spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_e0czIBcz?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=u_76Rbwp
spring.datasource.password=y7NT0CM5fwy1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
